### ISSUE TITLE
Regression: two columns no longer works

### ISSUE THREAD

**Issue by grahamperrin** [samber/refined-microsoft-teams#10]
`0.3.5`: two columns view is ineffective. 

Workaround: revert to `0.3.3`, https://addons.mozilla.org/firefox/downloads/file/3529425/refined_microsoft_teams-0.3.3-fx.xpi

https://addons.mozilla.org/addon/refined-microsoft-teams/versions/

**Comment by samber** [comment]
Hi @grahamperrin. Thanks for the report.

It works on my firefox browser. 🤔 

Can you verify if the checkbox is checked in the extension parameters ?

![image](https://user-images.githubusercontent.com/2951285/78561321-d026b500-7817-11ea-9316-fb97795936a5.png)

Do you see any error in developer console ?

**Comment by grahamperrin** [comment]
Thanks, 

> Can you verify if the checkbox is checked in the extension parameters ?

I did so before raising the issue. Cleared the checkbox then re-checked the box. 

I'll test with a newer boot environment with Firefox 75.0. 

At the time of writing (an inferior environment): 

```text
root@momh167-gjp4-8570p:~ # beadm list
BE       Active Mountpoint  Space Created
Waterfox -      -          383.2M 2020-03-10 18:24
r357746g NR     /           60.9G 2020-03-31 00:24
r359628b -      -           18.4G 2020-04-05 02:12
root@momh167-gjp4-8570p:~ # beadm activate r359628b
Activated successfully
root@momh167-gjp4-8570p:~ # date ; uptime ; uname -v
Mon Apr  6 18:45:28 BST 2020
 6:45PM  up 10:34, 4 users, load averages: 1.05, 1.66, 1.34
FreeBSD 13.0-CURRENT #51 r357746: Tue Feb 11 03:54:19 GMT 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
root@momh167-gjp4-8570p:~ # pkg query '%o %v %R' firefox
www/firefox 74.0_6,1 FreeBSD
root@momh167-gjp4-8570p:~ # 
```

In this environment, I necessarily ran Firefox 74.0 with the `--allow-downgrade` option. Related: 

* https://www.mozilla.org/en-US/firefox/75.0beta/releasenotes/
* https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75

– at a glance, before using the option, I saw nothing to worry about …

**Comment by grahamperrin** [comment]
The same with Firefox `75.0` as I found with `74.0`. 

Reproducible with `0.3.5` alone added to a refreshed profile. 

```grahamperrin@momh167-gjp4-8570p:~ % date ; uptime ; uname -v
Mon  6 Apr 2020 19:27:09 BST
 7:27p.m.  up 23 mins, 6 users, load averages: 1.82, 1.64, 1.02
FreeBSD 13.0-CURRENT #5 r359628: Sun Apr  5 00:25:58 BST 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 75.0,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

Immediately after installing `0.3.3` (without refreshing the Teams page), two columns appear. 

> Do you see any error in developer console ?

I see a couple of lines when switching from grid view from list, but these occur with both `0.3.5` _and_ `0.3.3` …

**Comment by grahamperrin** [comment]
With `0.3.5`: 

![image](https://user-images.githubusercontent.com/192271/78592558-2d812d00-783d-11ea-9c75-74f3d9d20648.png)

… the same with `0.3.3`.

**Comment by grahamperrin** [comment]
> Reproducible with `0.3.5` alone added to a refreshed profile.

No longer reproducible. 

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Wed 22 Apr 2020 02:05:55 BST
FreeBSD 13.0-CURRENT #52 r359750: Fri Apr 10 03:33:09 BST 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 75.0_1,1 poudriere
grahamperrin@momh167-gjp4-8570p:~ % 
```

Maybe `0.3.5` exposed a FreeBSD-specific bug that was present in Firefox `74.0` and the initial port of `75.0` (`75.0,1`) **but not** present in rc2 or rc3  (`75.0_1,1`). 

https://www.freshports.org/www/firefox/ | https://hg.mozilla.org/releases/mozilla-release/pushloghtml?startdate=2020-03-31&enddate=2020-04-04

**Comment by samber** [comment]
Hi @grahamperrin and sorry for the delay.

Nice to see it works ;)
