### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by AntonioFasano** [samber/refined-microsoft-teams#6]
Hello, in my organisation, we have _member_ and _guest_ users. It seems I cannot add those who are guests.
Can you confirm this and possibly give a workaround?

**Comment by samber** [comment]
Hi @AntonioFasano 

A fixed has been made in release 0.3.0 ;) 

Thanks for your report !

**Comment by AntonioFasano** [comment]
Thanks for the fix

**Comment by AntonioFasano** [comment]
Unfortunately, after testing, version 0.3.0 does not work at all for me.
I see the original add-member dialogue, without the extension bulk-import box.
I tested the extension in both Firefox and Chrome.

**Comment by samber** [comment]
Oooops

![](https://media.giphy.com/media/80TEu4wOBdPLG/giphy.gif)

A release 0.3.1 is in review process ;)

**Comment by AntonioFasano** [comment]
Tested 0.3.2 and works as expected. Thanks.
