### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [samber/refined-microsoft-teams#7]
Hi

https://addons.mozilla.org/en-GB/firefox/addon/refined-microsoft-teams/versions/0.3.2/updateinfo is empty and probably explains why (below) it's not possible to see release notes before deciding whether to proceed with an update. 

![image](https://user-images.githubusercontent.com/192271/76945445-68590a80-68fa-11ea-93cb-4b9314f2b1ad.png)

Please, can you make it habit to publish release notes at AMO? 

In the meantime I see (for example) https://github.com/samber/refined-microsoft-teams/commits/master

Thanks

**Comment by samber** [comment]
Oh yes definitely !

I just discovered we can edit the release. \o/
