### ISSUE TITLE
Tool fails under new multi-window feature (React)

### ISSUE THREAD

**Issue by markpete** [samber/refined-microsoft-teams#9]
First of all, greetings from MS Teams and thank you for contributing this great tool to our ecosystem.  I'm working on the new MultiWindow feature which is written in React and we are seeing your tool contribute a large number of failures in our telemetry data.

We've seen the following error over 8000 times in our TAP ring, so we wanted to make you aware of it as we work to bring MultiWindow public.  It looks like your chrome extension is looking for JQuery, which is not available in our React implementation.

Cheers and Thank You!

global_window_error: [{"name":"ReferenceError","message":"$ is not defined","stack":["ReferenceError: $ is not defined","at chrome-extension://bipffdldhfhcecjhcgklheahpkocojfk/scripts/multitenant-panel.js:1:74"]}]

**Comment by samber** [comment]
Hi @markpete and thanks for the report.

I just removed jQuery from this extension.

0.3.5 has been released. Roll out in progress.

I look forward the MultiWindow feature! Feel free to add me to beta as soon as it's available. 😆

**Comment by markpete** [comment]
Thanks!  That's great news.  You can see the feature in the Developer Preview ring.
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro

**Comment by markpete** [comment]
Actually, it looks like you might have missed a line in multitenant...
$(html).insertBefore('app-bar');

**Comment by samber** [comment]
I ended commenting the file ;)
